const products = [
    { id: 1, name: "3 Nights in Artsy Delaware Home!", description: "Wilmington, DE", price: 100000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/2028/7a0c07c4-5d8d-4f5a-be2c-746349579caf.jpg" },
    { id: 2, name: "All-Inclusive Hard Rock Hotel Getaway", description: "Amenia, NY", price: 200000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/1295/Pool%20at%20Sunset.JPG" },
    { id: 3, name: "Relax in Historic Hudson Valley B&B", description: "Amenia, NY", price: 300000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/840/gallery-02.jpg" },
    { id: 4, name: "Family All-Inclusive! Cancun or Punta Cana", description: "Valid at multiple locations", price: 100000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/2870/Cancun61.jpg" },
    { id: 5, name: "All-Inclusive Punta Cana Getaway", description: "Punta Cana, DO", price: 200000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/613/HRHCPC_Exterior_Drone_Beach11.JPG" },
    { id: 6, name: "5-Night Couple's Getaway to Hawaii!", description: "Honolulu, HI", price: 300000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/2866/Hawaii8.jpg" },
    { id: 7, name: "Luxury Parisian Apartment Stay", description: "Paris, France", price: 400000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/1006/carriagestop2.jpeg" },
    { id: 8, name: "Safari Adventure in Kenya", description: "Nairobi, Kenya", price: 500000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/VacationCertificates/Variation/1890/Primary.jpeg" },
    { id: 9, name: "Scenic Glacier Retreat", description: "Alaska, USA", price: 450000, image: "https://cloud.travelpledge.com/thumbnail/280x200/UploadFiles/Events/32166/17166/poconos1.png" }
];